const products = [
  {
    _id: "2",
    name: "All About Feelings",
    image: "/images/2.jpg",
    price: 39.99,
    discount: 10,
    description:
      " How are you feeling today? This fun, friendly and reassuring introduction to feelings is designed to help young children recognise, understand and name how they’re feeling and learn to talk about and manage their emotions in helpful ways.",
    category: "3+",
    countInStrock: 0,
    rating: 4.5,
    reviews: 4,
    ytblink: "https://youtube.com",
  },
  {
    _id: "3",
    name: "All About Feelings",
    image: "/images/3.jpg",
    price: 39.99,
    discount: 10,
    description:
      " How are you feeling today? This fun, friendly and reassuring introduction to feelings is designed to help young children recognise, understand and name how they’re feeling and learn to talk about and manage their emotions in helpful ways.",
    category: "3+",
    countInStrock: 0,
    rating: 4.5,
    reviews: 4,
    ytblink: "https://youtube.com",
  },
  {
    _id: "4",
    name: "All About Feelings",
    image: "/images/4.jpg",
    price: 39.99,
    discount: 10,
    description:
      " How are you feeling today? This fun, friendly and reassuring introduction to feelings is designed to help young children recognise, understand and name how they’re feeling and learn to talk about and manage their emotions in helpful ways.",
    category: "3+",
    countInStrock: 0,
    rating: 4.5,
    reviews: 4,
    ytblink: "https://youtube.com",
  },
  {
    _id: "5",
    name: "All About Feelings",
    image: "/images/5.jpg",
    price: 39.99,
    discount: 10,
    description:
      " How are you feeling today? This fun, friendly and reassuring introduction to feelings is designed to help young children recognise, understand and name how they’re feeling and learn to talk about and manage their emotions in helpful ways.",
    category: "3+",
    countInStrock: 0,
    rating: 4.5,
    reviews: 4,
    ytblink: "https://youtube.com",
  },
  {
    _id: "6",
    name: "All About Feelings",
    image: "/images/6.jpg",
    price: 39.99,
    discount: 10,
    description:
      " How are you feeling today? This fun, friendly and reassuring introduction to feelings is designed to help young children recognise, understand and name how they’re feeling and learn to talk about and manage their emotions in helpful ways.",
    category: "3+",
    countInStrock: 0,
    rating: 4.5,
    reviews: 4,
    ytblink: "https://youtube.com",
  },
  {
    _id: "9781474948197",
    name:
      "Lift-the-Flap First Questions and Answers Why Do Tigers Have Stripes?",
    image: "/images/9781474948197.jpg",
    price: 59.99,
    discount: 10,
    description:
      " Why do camels have humps? Why do turtles have shells? And why do fish have fins and birds have wings? Young animal lovers can find the answers to these questions and many more in this lift-the-flap information book. With colourful illustrations, simple text and chunky flaps to lift, and links to carefully selected websites with videos and activities.",
    category: "0+",
    countInStrock: 3,
    rating: 4,
    reviews: 6,
    ytblink: "https://youtube.com",
  },
  {
    _id: "9781474949071",
    name: "All About Families",
    image: "/images/9781474949071.jpg",
    price: 29.99,
    discount: 10,
    description:
      "What do families look like? Who’s in your family? And how can families change? With delightful illustrations, this glorious celebration of family diversity talks about lone-parent families, adoptive, foster, divorced, remarried, and mixed race families, and lots, lots more, showing little children that families come in all shapes and sizes.",
    category: "3+",
    countInStrock: 2,
    rating: 2,
    reviews: 1,
    ytblink: "https://youtube.com",
  },
  {
    _id: "9781474959063",
    name: "That's not my puppy",
    image: "/images/9781474959063.jpg",
    price: 100,
    discount: 70,
    description:
      "A sparkly special edition of the very first That’s not my… book to celebrate 20 years of That’s not my… books! Babies love the best-selling That’s not my… books with their bold illustrations, patches to stroke, and a mouse to spot on every page, all designed to develop sensory and language awareness.",
    category: "0+",
    countInStrock: 5,
    rating: 4.8,
    reviews: 24,
    ytblink: "https://www.youtube.com/watch?v=bzP60QIzBX0",
  },
  {
    _id: "9781474962605",
    name: "Poppy and Sam's Bedtime Stories",
    image: "/images/9781474962605.jpg",
    price: 39.99,
    discount: 0,
    description:
      "Snuggle up with Poppy and Sam, and enjoy these ten gentle tales of their adventures on Apple Tree Farm. Stories include a runaway tractor, a journey on an old steam train, a camping trip and lots more. Each story features charming illustrations by Stephen Cartwright, and there’s a Little Yellow Duck to spot in every picture too.",
    category: "2+",
    countInStrock: 4,
    rating: 3.2,
    reviews: 14,
    ytblink: "https://youtube.com",
  },
  {
    _id: "7",
    name: "All About Feelings",
    image: "/images/7.jpg",
    price: 39.99,
    discount: 10,
    description:
      " How are you feeling today? This fun, friendly and reassuring introduction to feelings is designed to help young children recognise, understand and name how they’re feeling and learn to talk about and manage their emotions in helpful ways.",
    category: "3+",
    countInStrock: 0,
    rating: 4.5,
    reviews: 4,
    ytblink: "https://youtube.com",
  },
  {
    _id: "8",
    name: "All About Feelings",
    image: "/images/8.jpg",
    price: 39.99,
    discount: 10,
    description:
      " How are you feeling today? This fun, friendly and reassuring introduction to feelings is designed to help young children recognise, understand and name how they’re feeling and learn to talk about and manage their emotions in helpful ways.",
    category: "3+",
    countInStrock: 0,
    rating: 4.5,
    reviews: 4,
    ytblink: "https://youtube.com",
  },
  {
    _id: "9",
    name: "All About Feelings",
    image: "/images/9.jpg",
    price: 39.99,
    discount: 10,
    description:
      " How are you feeling today? This fun, friendly and reassuring introduction to feelings is designed to help young children recognise, understand and name how they’re feeling and learn to talk about and manage their emotions in helpful ways.",
    category: "3+",
    countInStrock: 0,
    rating: 4.5,
    reviews: 4,
    ytblink: "https://youtube.com",
  },
  {
    _id: "10",
    name: "All About Feelings",
    image: "/images/10.jpg",
    price: 39.99,
    discount: 10,
    description:
      " How are you feeling today? This fun, friendly and reassuring introduction to feelings is designed to help young children recognise, understand and name how they’re feeling and learn to talk about and manage their emotions in helpful ways.",
    category: "3+",
    countInStrock: 0,
    rating: 4.5,
    reviews: 4,
    ytblink: "https://youtube.com",
  },
  {
    _id: "11",
    name: "All About Feelings",
    image: "/images/11.jpg",
    price: 39.99,
    discount: 10,
    description:
      " How are you feeling today? This fun, friendly and reassuring introduction to feelings is designed to help young children recognise, understand and name how they’re feeling and learn to talk about and manage their emotions in helpful ways.",
    category: "3+",
    countInStrock: 0,
    rating: 4.5,
    reviews: 4,
    ytblink: "https://youtube.com",
  },
  {
    _id: "9781474937115",
    name: "All About Feelings",
    image: "/images/9781474937115.jpg",
    price: 39.99,
    discount: 10,
    description:
      " How are you feeling today? This fun, friendly and reassuring introduction to feelings is designed to help young children recognise, understand and name how they’re feeling and learn to talk about and manage their emotions in helpful ways.",
    category: "3+",
    countInStrock: 0,
    rating: 4.5,
    reviews: 4,
    ytblink: "https://youtube.com",
  },
  {
    _id: "9781474948197",
    name:
      "Lift-the-Flap First Questions and Answers Why Do Tigers Have Stripes?",
    image: "/images/9781474948197.jpg",
    price: 59.99,
    discount: 10,
    description:
      " Why do camels have humps? Why do turtles have shells? And why do fish have fins and birds have wings? Young animal lovers can find the answers to these questions and many more in this lift-the-flap information book. With colourful illustrations, simple text and chunky flaps to lift, and links to carefully selected websites with videos and activities.",
    category: "0+",
    countInStrock: 3,
    rating: 4,
    reviews: 6,
    ytblink: "https://youtube.com",
  },
  {
    _id: "9781474949071",
    name: "All About Families",
    image: "/images/9781474949071.jpg",
    price: 29.99,
    discount: 10,
    description:
      "What do families look like? Who’s in your family? And how can families change? With delightful illustrations, this glorious celebration of family diversity talks about lone-parent families, adoptive, foster, divorced, remarried, and mixed race families, and lots, lots more, showing little children that families come in all shapes and sizes.",
    category: "3+",
    countInStrock: 2,
    rating: 2,
    reviews: 1,
    ytblink: "https://youtube.com",
  },
  {
    _id: "9781474959063",
    name: "That's not my puppy",
    image: "/images/9781474959063.jpg",
    price: 100,
    discount: 70,
    description:
      "A sparkly special edition of the very first That’s not my… book to celebrate 20 years of That’s not my… books! Babies love the best-selling That’s not my… books with their bold illustrations, patches to stroke, and a mouse to spot on every page, all designed to develop sensory and language awareness.",
    category: "0+",
    countInStrock: 5,
    rating: 4.8,
    reviews: 24,
    ytblink: "https://www.youtube.com/watch?v=bzP60QIzBX0",
  },
  {
    _id: "9781474962605",
    name: "Poppy and Sam's Bedtime Stories",
    image: "/images/9781474962605.jpg",
    price: 39.99,
    discount: 0,
    description:
      "Snuggle up with Poppy and Sam, and enjoy these ten gentle tales of their adventures on Apple Tree Farm. Stories include a runaway tractor, a journey on an old steam train, a camping trip and lots more. Each story features charming illustrations by Stephen Cartwright, and there’s a Little Yellow Duck to spot in every picture too.",
    category: "2+",
    countInStrock: 4,
    rating: 3.2,
    reviews: 14,
    ytblink: "https://youtube.com",
  },
  {
    _id: "9781474981323",
    name: "Don't tickle the pig",
    image: "/images/9781474981323.jpg",
    price: 19.99,
    discount: 10,
    description:
      "You'd better not tickle the pig... because it just might oink if you do! Little children won't be able to resist pressing the soft touchy-feely patches to hear the different farm animals in this delightful novelty book. After the pig, cow, sheep and horse have been tickled, they all join in at the end, making their noises along with a hilarious rendition of the Old Macdonald Had a Farm tune.",
    category: "3+",
    countInStrock: 10,
    rating: 4.1,
    reviews: 7,
    ytblink: "https://youtube.com",
  },
  {
    _id: "9781474989770",
    name: "Little Children's Under the Sea Activity Book",
    image: "/images/9781474989770.jpg",
    price: 19.99,
    discount: 10,
    description:
      "This colourful activity book is brimming with with fun puzzles to keep little children entertained for hours. There are things to spot, ocean animals to match, tropical fish to colour, lots of drawing and doodling activities, spot-the-difference puzzles and much more.",
    category: "3+",
    countInStrock: 23,
    rating: 5,
    reviews: 5,
    ytblink: "https://youtube.com",
  },
];

module.exports = products;
